spring.application.name=Chapter03

spring.main.web-application-type=servlet

# 테스트에 사용할 데이터를 프로퍼티로 등록한다. 
author.name=TESTER
author.age=45

#서버 포트 설정
server.port=8080

#DataSource에 초기화할 정보 설정
spring.datasource.hikari.driver-class-name=org.h2.Driver
spring.datasource.hikari.jdbc-url=jdbc:h2:tcp://localhost/~/test
spring.datasource.hikari.username=sa
spring.datasource.hikari.password=

## 로깅 설정
## 로그 레벨설정
#logging.level.com.rubypaper=info
#logging.level.org.springframework=warn
#
## 파일에 로그 출력
#logging.file.name=src/main/resources/logs/board_log.log
#
## 로그 패턴 설정
#logging.pattern.console=%d{yyyy:mm:dd HH:mm:ss} %-5level ===> [%thread] %logger{35} ::: %msg %n
#logging.pattern.file=%d{yyyy:mm:dd HH:mm:ss} %-5level ===> [%thread] %logger{35} ::: %msg %n