DROP TABLE USERS;

CREATE TABLE USERS(
 USERNAME VARCHAR2(10) PRIMARY KEY,	-- 아이디
 PASSWORD VARCHAR2(100),			-- 비밀번호를 나중에 암호화해서 저장한다.
 NAME VARCHAR2(30),					-- 이름
 ROLE VARCHAR2(12),
 ENABLED BOOLEAN
);
INSERT INTO USERS VALUES('manager', 'test123', '매니저', 'MANAGER', TRUE);
INSERT INTO USERS VALUES('admin', 'test123', '어드민', 'ADMIN', TRUE);
