spring.application.name=Chapter06

# JSP 파일들이 등록될 디렉토리 지정(src/main/webapp/WEB-INF/board)
spring.mvc.view.prefix=/WEB-INF/board/

# DataSource에 초기화할 정보 설정
spring.datasource.hikari.driver-class-name=org.h2.Driver
spring.datasource.hikari.jdbc-url=jdbc:h2:tcp://localhost/~/test
spring.datasource.hikari.username=sa
spring.datasource.hikari.password=

# JPA 관련 설정(META-INF/persistece.xml 설정을 대체한다.)
spring.jpa.database=h2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update